[package]
name = "bevy-hid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "1.4.2"
hid-and-seek = { version = "0.1.2" }
bevy = { git = "https://github.com/bevyengine/bevy" }